### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by varunagrawal**
Removed non-code files and updated folder names.

### CODE REVIEW

**Review by dellaert — CHANGES_REQUESTED** [review]
I appreciate this, but it's probably not a great idea to rename this folder after I sent instructions to frankcvs with the old name.

**Comment by varunagrawal** [comment]
Perhaps merge once everyone has responded and added their details?

**Comment by varunagrawal** [comment]
I can update the PR once we have everything set.

**Comment by dellaert** [comment]
Please undo the name change- I see no reason for it. I like the other changes.

**Comment by dellaert** [comment]
Closing this PR. Please make changes to your personal entry in a separate PR.

**Pull request closed without merging**
