### PR TITLE
Source

### PR DESCRIPTION
**Pull request by swarrier246**
Adding twitter feed. Will be integrating Travis CI to automate building with custom jekyll plugins

### CODE REVIEW

**Review by dellaert — APPROVED** [review]
Yay !!!!

**Comment by dellaert** [comment]
A bit strange: what is the “source” branch? If you want any changes on the website, I think you need to merge into the gh-pages branch.

**Comment by swarrier246** [comment]
so gh-pages cannot build anything that uses custom jekyll plugins-which twitter does. So I had set up a travis CI(when I was working in my forked repo) to build from source and publish the generated static pages to gh-pages branch, which can then publish it. I don't yet have a travis CI setup for this repo, I wasn't sure how to do it for borglab. Had asked Varun for help with this too, will reach out again today

**Comment by dellaert** [comment]
Hmmmm, yeah, I'm not loving that. If you take a look at the gtsam.org repo, you'll see it does twitter but it renders fine on gh-pages. That seems to say there is a gh-pages compatible way?

**Comment by swarrier246** [comment]
That is intriguing. Will take a look, thanks for pointing it out!

**Pull request merged**
